# Generated by Django 3.2.6 on 2021-08-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='picture',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='000-000-0000-0000', max_length=20, verbose_name='phone number'),
        ),
    ]
